### PR TITLE
Delete profile command

### LINKED ISSUE #46: As a user, I want to delete my past achievements and work experience
So that my user profile is not cluttered.

### PR DESCRIPTION
**Pull request by orzymandias**

### CODE REVIEW

**Review by seanjyjy — COMMENTED** [review]
Can add the todo or javadocs and it is good to merge.

**Comment by orzymandias** [comment]
> Can add the todo or javadocs and it is good to merge.

Which file/line are you referring to?

**Comment by seanjyjy** [comment]
> > Can add the todo or javadocs and it is good to merge.
> 
> Which file/line are you referring to?

DeleteProfleCommand class and maybe its constructor? incase forget in the future

**Comment by seanjyjy** [comment]
Will merge this first

**Pull request merged**
