### PR TITLE
Add test cases for internship

### LINKED ISSUE #160: Update status util

### PR DESCRIPTION
**Pull request by keanecjy**
Create unit test for all classes in internship and make sample internship data for tests
Update Status util class

### CODE REVIEW

**Review by ZoroarkDarkrai — COMMENTED** [review]
I think it's okay just I find many hard coded strings can be converted to const. If urgent can merge now and fix later?

**Comment by keanecjy** [comment]
> I think it's okay just I find many hard coded strings can be converted to const. If urgent can merge now and fix later?

Is it not normal to use hard-coded strings for test cases? Could you point on where exactly is the issue? Thanks

**Comment by ZoroarkDarkrai** [comment]
> > I think it's okay just I find many hard coded strings can be converted to const. If urgent can merge now and fix later?
> 
> Is it not normal to use hard-coded strings for test cases? Could you point on where exactly is the issue? Thanks

I mean the toString, equality, hashcode tests. Could use VALID_WAGE, VALID_PERIOD, etc? If it's a better practice to use "Sunday", "React Native", etc. it's fine then.

**Comment by keanecjy** [comment]
> > > I think it's okay just I find many hard coded strings can be converted to const. If urgent can merge now and fix later?
> > 
> > 
> > Is it not normal to use hard-coded strings for test cases? Could you point on where exactly is the issue? Thanks
> 
> I mean the toString, equality, hashcode tests. Could use VALID_WAGE, VALID_PERIOD, etc? If it's a better practice to use "Sunday", "React Native", etc. it's fine then.

Not too sure what's the correct which is the correct way, but I just thought that doing it this way by writing 2 strings that are different objects would be better since we will be comparing periods with different strings in the actual implementation too

**Comment by ZoroarkDarkrai** [comment]
> > > > I think it's okay just I find many hard coded strings can be converted to const. If urgent can merge now and fix later?
> > > 
> > > 
> > > Is it not normal to use hard-coded strings for test cases? Could you point on where exactly is the issue? Thanks
> > 
> > 
> > I mean the toString, equality, hashcode tests. Could use VALID_WAGE, VALID_PERIOD, etc? If it's a better practice to use "Sunday", "React Native", etc. it's fine then.
> 
> Not too sure what's the correct which is the correct way, but I just thought that doing it this way by writing 2 strings that are different objects would be better since we will be comparing periods with different strings in the actual implementation too

Sure then! I just thought maybe using constants could make it easier to see, that creating an object with the same input will result to an equal one. Like 2 objects created with VALID_PERSON_ALICE are equals but not with one created with VALID_PERSON_BOB.
LGTM!

**Review by ZoroarkDarkrai — APPROVED** [review]

**Pull request merged**
