### PR TITLE
Add application, internship json tests

### PR DESCRIPTION
**Pull request by ZoroarkDarkrai**
Add application item, application item json, internship item json tests

### CODE REVIEW

**Comment by keanecjy** [comment]
I don't think you should be writing tests for ApplicationItem, Status, and StatusDate? Since we should be writing tests for our own classes and not helping others write their tests

**Comment by ZoroarkDarkrai** [comment]
> I don't think you should be writing tests for ApplicationItem, Status, and StatusDate? Since we should be writing tests for our own classes and not helping others write their tests

Oh, I think I misunderstood then. When I said I couldn't do the storage ones then because lack of sample data, I think someone said I should do the application ones. So, do you want me to remove them?

**Comment by keanecjy** [comment]
> > I don't think you should be writing tests for ApplicationItem, Status, and StatusDate? Since we should be writing tests for our own classes and not helping others write their tests
> 
> Oh, I think I misunderstood then. When I said I couldn't do the storage ones then because lack of sample data, I think someone said I should do the application ones. So, do you want me to remove them?

Oh what I meant was create sample data for the storage tests and not to test the application classes themselves. So the rest of the files can stay except for `ApplicationItemTest`, `StatusTest` and `StatusDateTest`. Hope this clarifies!

**Comment by ZoroarkDarkrai** [comment]
> > > I don't think you should be writing tests for ApplicationItem, Status, and StatusDate? Since we should be writing tests for our own classes and not helping others write their tests
> > 
> > 
> > Oh, I think I misunderstood then. When I said I couldn't do the storage ones then because lack of sample data, I think someone said I should do the application ones. So, do you want me to remove them?
> 
> Oh what I meant was create sample data for the storage tests and not to test the application classes themselves. So the rest of the files can stay except for `ApplicationItemTest`, `StatusTest` and `StatusDateTest`. Hope this clarifies!

Ok, removed them!

**Review by orzymandias — APPROVED** [review]
LGTM! Could you update PR title?

**Pull request merged**
