### PR TITLE
Update Edit Profile Command in DG

### LINKED ISSUE #212: Add edit item feature to Developer Guide

### PR DESCRIPTION
**Pull request by orzymandias**
PR Overview
* Add edit profile command for developer guide
* Add edit profile command diagrams for developer guide (sequence diagram)
* Update Edit commands implementation to conform to LOD

### CODE REVIEW

**Comment by seanjyjy** [comment]
Overall LGTM to merge, just need to fix the image link. Think there is a typo in the png file itself

**Comment by orzymandias** [comment]
> Overall LGTM to merge, just need to fix the image link. Think there is a typo in the png file itself

Thank you, Good catch!

**Comment by seanjyjy** [comment]
Just some comments for you to consider, not very sure if it is right or wrong.
For `sd execute edit me command`, you might want to include what is return in the `getProfileList()` perhaps.
And for void methods like `setItem` and `setProfileItem` i believe the return arrows could be omitted as it doesn't bring any value and it does help to reduce cluttering. 

However, if you think that it is fine, then do let me know as it is good to merge already.

**Comment by orzymandias** [comment]
> Just some comments for you to consider, not very sure if it is right or wrong.
> For `sd execute edit me command`, you might want to include what is return in the `getProfileList()` perhaps.
> And for void methods like `setItem` and `setProfileItem` i believe the return arrows could be omitted as it doesn't bring any value and it does help to reduce cluttering.
> 
> However, if you think that it is fine, then do let me know as it is good to merge already.

Thanks for the feedback! I have updated the `getProfileList()` depiction but I think I will keep the return arrows for the time being since I think the clutter is still ok and I see that Shawn has also used them to indicate that the methods has completed its execution.

**Comment by seanjyjy** [comment]
LGTM. Good job

**Pull request merged**
