### PR TITLE
Update developer guide and user guide

### LINKED ISSUE #239: Add logic diagrams in the DG

### LINKED ISSUE #254: Add User Stories and Use Cases for skills matching in DG

### PR DESCRIPTION
**Pull request by keanecjy**
PR Overview:
- Update developer guide to include match command in user stories
- Added the Documentation, logging, testing, configuration, dev-ops to developer guide
- Add logic section of developer guide
- Update user guide images for application to use future dates

### CODE REVIEW

**Comment by seanjyjy** [comment]
There are issues with the formatting in your new code for each of the note and tip

**Comment by keanecjy** [comment]
> There are issues with the formatting in your new code for each of the note and tip

These show up okay for the html file because they are not markdown format!

**Review by ZoroarkDarkrai — APPROVED** [review]
Lgtm! Just a question is there any reason you renamed the files add,edit,find application1.png ?

**Comment by ZoroarkDarkrai** [comment]
there seems to be no new LogicClassDiagram.png or DeleteSequenceSequenceDiagram.png?

**Comment by keanecjy** [comment]
> there seems to be no new LogicClassDiagram.png or DeleteSequenceSequenceDiagram.png?

Yes, I am in the midst of updating them.

**Comment by seanjyjy** [comment]
LGTM

**Pull request merged**
