### PR TITLE
Update User Stories and add Model diagram to DG

### LINKED ISSUE #224: Update User Stories for DG

### LINKED ISSUE #246: Model Diagram for DG

### PR DESCRIPTION
**Pull request by shawn-nyk**
Resolves #224 
Resolves #246

### CODE REVIEW

**Comment by seanjyjy** [comment]
For the model diagram, I believe that the arrow from the `ApplicationItem`, etc should be in solid line to the `Item` as ours is an Inheritance relationship. 

I am not sure but maybe it is `ViewManager` and `TabManager` rather than `View` and `Tab`

I am not sure if `ApplicationItem` has a composition with `InternshipItem`? But rather there should a relationship between `CompanyItem` and `ApplicationItem`

**Comment by shawn-nyk** [comment]
> For the model diagram, I believe that the arrow from the `ApplicationItem`, etc should be in solid line to the `Item` as ours is an Inheritance relationship.

Thanks for catching this! Will make the change.

> I am not sure but maybe it is `ViewManager` and `TabManager` rather than `View` and `Tab`

Hmm, looking at `ModelManager`,  it stores a `Tab` and `View` as its fields though, therefore it should be as per the current diagram?

> I am not sure if `ApplicationItem` has a composition with `InternshipItem`? But rather there should a relationship between `CompanyItem` and `ApplicationItem`


Ah yep I believe you're right, `ApplicationItem` should not have a composition with `InternshipItem`, and `InternshipItem` should also not have a composition with `CompanyName`. But `CompanyItem` and `ApplicationItem` have no relationship I believe, because checking the code for `CompanyItem`, it is not aware that `ApplicationItem` exists.

Thanks again for highlighting all the above, do let me know if this is ok!

**Comment by seanjyjy** [comment]
> Hmm, looking at ModelManager, it stores a Tab and View as its fields though, therefore it should be as per the current diagram?

Ah yes you're right i have missed out that.

1) Sorry that i missed out again but I think the ProfileItemCategory is an `enum` class.
2) Not sure if the association labels are pointing in the wrong direction(is this a plantuml limitation? if it is then nvm)
3) not sure if package is the right word to use, perhaps they are classes?

Just a thought
1) I think the user stories are arranged in Company -(internship)- application - profile - general. Then maybe the 1st and 2nd user stories should be put in the general section instead, for consistency in the arrangement.

Otherwise just some nits to fix and it is good to merge!

**Comment by shawn-nyk** [comment]
> 1. Sorry that i missed out again but I think the ProfileItemCategory is an `enum` class.

Ah my bad, good catch! Will fix that too.

> 2. Not sure if the association labels are pointing in the wrong direction(is this a plantuml limitation? if it is then nvm)

Yup it's a plantuml thing haha, but I think it should still be quite obvious to the reader as to which direction to read the label, I hope!

> 3. not sure if package is the right word to use, perhaps they are classes?

Good point, I thought about this one quite a bit yesterday and settled on "package" eventually cos I realised that if I were to say that the diagrams are a breakdown of the `Company`, `Application`, `Internship` and `Profile` "classes", it may not be accurate because there are no classes actually called `Company`, `Application`, `Internship` and `Profile` - those are the names of our packages and within them are the numerous classes as shown in the diagram. Do let me know if there is a better term we could use though!

> 1. I think the user stories are arranged in Company -(internship)- application - profile - general. Then maybe the 1st and 2nd user stories should be put in the general section instead, for consistency in the arrangement.

Sounds good, will shift the stories!

**Comment by seanjyjy** [comment]
LGTM good job

**Pull request merged**
